### PR TITLE
update notebook

### PR DESCRIPTION
**Pull request by jGaboardi**
* Included:
  * update location to St. Gallen – full notebook runs in ≈3 minutes (on my machine) xref #1
    * how does this runtime seem? I am open to trying other locations if it is too long 
  * use proper CRS/EPSG, may have been been causing the memory leak xref #3 
  * clean up formatting, etc.
  * add some `warning` catchers
* Still needs
  * (probably lots more love?)
  * updates of actual slide deck xref #4 
  * etc.?

### CODE REVIEW

**Comment by martinfleis** [comment]
Thanks! I think that St Gallen works here. Runtime on my machine is 2-3 minutes of which 40s is osmnx call to get buildings.

> use proper CRS/EPSG, may have been been causing the memory leak xref 

What do you mean by a proper CRS? The original notebook also uses a national CRS.

> add some `warning` catchers

Can we fix this in momepy and make a patch release? I'd rather not have to catch warnings if we can affect them.

**Review by martinfleis — APPROVED** [review]
I think we can merge and do other changes as follow ups.

**Comment by jGaboardi** [comment]
> What do you mean by a proper CRS? The original notebook also uses a national CRS.

I had forgotten to swap out the Czech CRS (`5514`) with the Swiss one (`2056`). After I did that the notebook seemed to run more efficiently, though it may have been for different reasons all together...

**Comment by jGaboardi** [comment]
> Can we fix this in momepy and make a patch release? I'd rather not have to catch warnings if we can affect them.

I'll take another pass at this before we merge to isolate these out. My recollection is that they were from `ipywidgets`, `numpy`, etc.

**Comment by martinfleis** [comment]
Ok. Feel free to merge this.

**Comment by jGaboardi** [comment]
OK, will merge now and iterate back to see about the 2 last troublesome warnings from #8.

**Pull request merged**
