### PR TITLE
links for GH handles

### PR DESCRIPTION
**Pull request by jGaboardi**
One more "final" nit: add links for GH handles

### CODE REVIEW

**Comment by jGaboardi** [comment]
@martinfleis should we also meet at some point to test out Airmeet?

**Comment by martinfleis** [comment]
That would need to happen either today or tomorrow eve (my time zone).

**Comment by jGaboardi** [comment]
How about ≈30 from now? [1:30 EDT / 7:30 CET]

**Comment by martinfleis** [comment]
That should work. See you there!

**Pull request merged**
