### PR TITLE
plot weights

### LINKED ISSUE #15: pin dependencies
* `pandas` – 1.4.4
* `matplotlib` – 3.5.3

@martinfleis Any other to add to the list?

### PR DESCRIPTION
**Pull request by jGaboardi**
@martinfleis a few weeks back I think you mentioned that it might be nice to include some plotting of weights in here (maybe I'm mistaken?). This PR includes several weights plots. I think they look nice, but sure how they would fit in with the workshop. Let me know what you think. I won't be offended if you think they don't work well here.

Resolves https://github.com/martinfleis/sdss22-workshop/issues/15

### CODE REVIEW

**Comment by martinfleis** [comment]
Yes, this is what I meant. Thanks!

One note - can we override how splot styles those polygons? Because the last figure of queen on buildings is weird as building outline is white on a white background, which looks like a gap.

**Comment by martinfleis** [comment]
I would also try to squeeze those cells a bit. Like:

```py
f, ax = plot_spatial_weights(
    buildings_q1,
    buildings,
    indexed_on="uID",
    figsize=(7, 7),
    node_kws=dict(ec="k", fc="salmon", markersize=7.5, zorder=2),
    edge_kws=dict(ec="salmon", lw=1, zorder=1)
)
ax.set_xlim(2746300, 2746700)
ax.set_ylim(1254300, 1254700)
```

**Comment by jGaboardi** [comment]
> I would also try to squeeze those cells a bit.

Yep. Still a work in progress.

**Comment by jGaboardi** [comment]
> can we override how splot styles those polygons?

This is something that was partially [addressed last year](https://github.com/pysal/splot/blob/fa5304e305d2d7b2e7e46c311f00f86785de4388/splot/_viz_esda_mpl.py#L934-L944) for plotting LISA from `esda` (though the flexibility for a user to set edge colors themselves is not present). However, this does not extend to [`plot_spatial_weights`](https://github.com/pysal/splot/blob/fa5304e305d2d7b2e7e46c311f00f86785de4388/splot/_viz_libpysal_mpl.py#L151). Wondering if we should:
1. stick with current plots and explain the situation
2. hack our our plotting method for this workshop
3. put in a PR to change this one function in `splot` with a note for future attention to other functions.

**Comment by martinfleis** [comment]
Let's just ignore it and open an issue in splot.

**Comment by jGaboardi** [comment]
@martinfleis I think the tutorial notebook is in a *pretty good place*.

**Comment by jGaboardi** [comment]
Resolves #15

**Comment by jGaboardi** [comment]
Considering #14, do we want to add a References section? I sometimes add to notebook tutorials, and sometimes not.

**Comment by jGaboardi** [comment]
Also, still need to update the actual slide deck and links within (if we want to do that) – https://github.com/martinfleis/sdss22-workshop/issues/4.

**Comment by martinfleis** [comment]
> Considering https://github.com/martinfleis/sdss22-workshop/issues/14, do we want to add a References section? I sometimes add to notebook tutorials, and sometimes not.

Yeah, SDSS folks may find it welcome to click through to more scientific material.

> Resolves https://github.com/martinfleis/sdss22-workshop/issues/15

This needs to be in the first comment to automatically close the issue.

> Also, still need to update the actual slide deck and links within (if we want to do that) – https://github.com/martinfleis/sdss22-workshop/issues/4.

Yeah, that is on my to-do. May be finished on Thursday eve though.

**Review by martinfleis — APPROVED** [review]
I think this can be merged.

**Comment by jGaboardi** [comment]
> Yeah, SDSS folks may find it welcome to click through to more scientific material.

OK, I can add to this the another.

**Pull request merged**
